### ISSUE TITLE
ostk.devのCI/CD環境をつくりたい

### ISSUE THREAD

**Issue by nisshii0313** [takumaosada/ostk_profile_site#1]
- Travis
無料、簡潔に書きやすい

- Circle CI
無料(private repositoryにするとお金かかる)、ちょっと複雑になるけど色々書ける

- Github Actions
無料(beta版登録が必要)、GUIがあるから書きやすい

**Comment by nisshii0313** [comment]
https://travis-ci.org/
https://circleci.com/signup/
https://github.com/features/actions
とりあえずどれかに登録しよ ❤️

**Comment by ostk0069** [comment]
オヌヌメは？(自作ライブラリ作成する時に参考にしたい)

**Comment by nisshii0313** [comment]
おぬぬめはナウいからGithub Actions
(ymlの書き方ちょっと独特だけど、嫌だったらGUIでも設定できる🙆)

**Comment by ostk0069** [comment]
とりあえず登録済ませて適当にやってたらversionが古いことを指摘され、勝手にそれを解消するためのPRが自動生成されて意味わからん、凄いってなってる。

**Comment by nisshii0313** [comment]
vulnerability error検知できるらしいからそれが発火したっぽさみやね
